baseURL = "https://hibou107.github.io"
languageCode = "en-us"
title = "My technical blog"
pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
theme = "coder" # set the theme
disqusShortname = "hibou107"

[params] # theme parameters
    author = "Hoai Nam NGUYEN" # author's name
    info = "Programmer" # author's job title or info
    description = "My technical blog" # site description
    keywords = "blog,developer,personal,programming" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = false
    
# Social links
[[params.social]]
    name = "Github"
    weight = 1
    url = "https://github.com/hibou107"

[[params.social]]
    name = "LinkedIn"
    weight = 3
    url = "https://www.linkedin.com/in/hoai-nam-nguyen/"

# Menu links
[[menu.main]]
    name = "Blog"
    weight = 1
    url  = "/posts/"
[[menu.main]]
    name = "About"
    weight = 2
    url = "/about/"