baseURL = "https://hibou107.github.io"
languageCode = "en-us"
title = "My technical blog"
pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true
theme = "sam" # set the theme
disqusShortname = "hibou107"

[params] # theme parameters
    author = "Hoai Nam NGUYEN" # author's name
    info = "Programmer" # author's job title or info
    description = "My technical blog" # site description
    keywords = "blog,developer,personal,programming" # site keywords

    # wether you want to hide copyright and credits in the footer
    hideCredits = false
    hideCopyright = false
    

[[params.mainMenu]]
    link = "/about"
    text = "About"

[[params.mainMenu]]
    link = "/posts"
    text = "Blog"

[[params.mainMenu]]
    link = "https://github.com/hibou107"
    text = "Github"

[[params.mainMenu]]
    link = "https://stackexchange.com/users/315982/nam"
    text = "StackOverFlow"

[[params.mainMenu]]
    link = "https://www.linkedin.com/in/hoai-nam-nguyen/"
    text = "LinkedIn"